Repository r-anime/surveysite, pull requests merged in 2021-07, with the labels that each got.

#48 Automate survey opening/closing
  survey/admin.py
  survey/migrations/0012_auto_20210703_2124.py
  survey/models.py
  survey/static/survey/scss/index.scss
  survey/templates/survey/form.html
  survey/templates/survey/index_survey.html
  survey/templates/survey/index_survey_upcoming.html
  survey/views/index.py
  survey/views/mixins.py
  survey/views/results.py
Labels: back-end, enhancement

#54 Gender-specific results
  .gitignore
  survey/static/survey/js/fullresults.js
  survey/static/survey/js/results.js
  survey/static/survey/scss/results.scss
  survey/templates/survey/fullresults.html
  survey/templates/survey/results.html
  survey/templates/survey/results_item_group-js.html
  survey/templates/survey/results_item_group.html
  survey/templates/survey/results_item_hidden-group.html
  survey/templates/survey/results_item_table-base.html
  survey/templates/survey/results_item_table-pair-js.html
  survey/templates/survey/results_item_table-pair.html
  survey/templates/survey/results_item_table-with-top3-js.html
  survey/templates/survey/results_item_table-with-top3.html
  survey/views/results.py
Labels: enhancement, front-end

#57 Move virtualenv location on server
  .github/workflows/deploy.yml
Labels: devops
